version: "3.9"
services:
  server:
    image: nexus.local:8080/rhink/temperature_server:latest
    ports:
      - "9990:9990"
      - "8081:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - temperature_network
  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - temperature_database:/var/lib/postgres/data
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - temperature_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 5s  

volumes:
  temperature_database:

networks:
  temperature_network: